### ISSUE TITLE
Sửa lỗi thanh tiến trình không cập nhật tại layout 2 - Colour and count the beads.

### ISSUE THREAD

**Issue by lehuunghia03112000** [lhtrung11/Number-of-Objects#4]
Thanh tiến trình không thay đổi so với layout 1

**Comment by lhtrung11** [comment]
chỉnh lại cái set invisible ở layout 1 và set visible ở layout 2 xem

**Comment by lehuunghia03112000** [comment]
Lỗi trên là do đã tạo mới layout 2 ở chế độ duplicate của layout 1 ( layout mới nhưng vẫn dùng chung phần mã nguồn của layout 1 )
