### ISSUE TITLE
cách sắp xếp phù hợp với vật thể trên vật thể khác

### ISSUE THREAD

**Issue by lhtrung11** [lhtrung11/Number-of-Objects#5]
làm sao để nhân đống hoa quả lên nhiều lần và xếp chúng 1 cách ngẫu nhiên vào từng hộp

**Comment by lhtrung11** [comment]
tại game 3

**Comment by lehuunghia03112000** [comment]
- Để tạo nhiều đối tượng giống một đối tượng đã có: click chuột phải -> đối tượng cần nhân bản -> clone object type. 
- Đặt vị trí các quả giống như trong bản ở trang DragonLearn, không cần phải chọn ví trí ngẫu nhiên.

**Comment by lhtrung11** [comment]
cái ngẫu nhiên mới là cái ấn tượng đó, bài của tôi trên dragonlearn cũng như vậy mà

**Comment by lhtrung11** [comment]
the problems had solved
