### ISSUE TITLE
vòng lặp khi trả lời sai không hoạt động

### ISSUE THREAD

**Issue by lhtrung11** [lhtrung11/Number-of-Objects#6]
khi trả lời sai câu bất kì ở màn 2 -> 6, thanh tiến trình vẫn tiếp diễn như bình thường và k quay lại màn chơi đã sai

**Comment by lehuunghia03112000** [comment]
Gửi file đó lên đi.

**Comment by lhtrung11** [comment]
t không làm được vòng lặp nữa, khó quá, làm 1 màn giới thiệu và màn biểu tượng cho các màn giống nhau thôi vậy
